<?php

/**
 * CQXR開発テスト
 * CQXR開発テスト用API群
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/**
 * get _0
 * Summary: 指定ユーザー表示
 * Notes: 指定ユーザーを表示するAPI
 * Output-Formats: [application/json]
 */
Route::get('/user/{user_id}', 'CollectionController@_0');
/**
 * get 
 * Summary: ユーザー一覧を表示
 * Notes: ユーザー一覧を表示するAPI
 * Output-Formats: [application/json]
 */
Route::get('/userlist', 'CollectionController@');

Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});
