<?php

/**
 * CQXR開発テスト
 * CQXR開発テスト用API群
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class CollectionController extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation _0
     *
     * 指定ユーザー表示.
     *
     * @param int $userId ユーザーID (required)
     *
     * @return Http response
     */
    public function _0($userId)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing _1 as a get method ?');
    }
    /**
     * Operation 
     *
     * ユーザー一覧を表示.
     *
     *
     * @return Http response
     */
    public function ()
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing  as a get method ?');
    }
}
